const {
  Schema,
  model
} = require('mongoose');

const userSchema = new Schema(
  {
    email: {
      type: String,
      required: [true, 'Email is required'],
      match: [/^\S+@\S+\.\S+$/, 'Please use a valid email address.'],
      unique: true,
      lowercase: true,
      trim: true
    },
    passwordHash: {
      type: String,
      required: [true, 'Password is required.']
    },
    ironhacker: {
      type: Boolean,
    },
    //EMBEDDED IRONHACKER PROPERTY ? DOES THE REQUIRED FIELD CAN BE CONDITIONAL
    profileImgSrc: String,
    firstName: String,
    lastName: String,
    expertise: String,
    gitHub: String,
    linkedIn: String,
    // courses: String,
    courses: {
      type: String,
      enum: ['Web-Dev', 'UX/UI', 'Data', 'Cyber_Security'] // undefined to solve user model validation generated by enum
    },
    promo: String,
    // campus: String,
    campus: {
      type: String,
      enum: ['Amsterdam', 'Barcelona', 'Berlin', 'Lisboa', 'Madrid', 'Mexico', 'Miami', 'Paris', 'Remote', 'Sao_Paulo']
    },
    format: { type: String, enum: ['Full-Time', 'Part-Time'] }, // PART-TIME OU FULL-TIME
    current_location: String, //WHAT LOCATION ATTRIBUTE IS ABOUT?
    projects: {
      type: Schema.Types.ObjectId,
      ref: 'Project'
    },
    // OBJET DANS OBJET POUR user AND recruiter MODEL REQUIRED FIELD ? REQUIRED = WE CAN'T MISS IT
    //   recruiter: {
    //     type: Boolean,
    //   },
    //   title: {
    //     type: String,
    //     required: [true, "What is your current position ?"]
    //   },
    //   company: {
    //     type: String,
    //     required: [true, "Please enter your company"]
    //   },
    //   contact: {
    //     type: String,
    //   },
    //   favorites: [String]
    // },
  },
  {
    timestamps: true
  }
);

module.exports = model('User', userSchema);